name: Pact Publish Consumer

on:
  push:
    branches: [main]

jobs:
  pact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install --production=false
      
      - name: Run tests and generate Pact files
        run: npm run test

      - name: Publish Pacts
        run: |
          export PACT_BROKER_BASE_URL="${{ secrets.PACT_BROKER_BASE_URL }}"
          export PACT_BROKER_TOKEN="${{ secrets.PACT_BROKER_TOKEN }}"
          export PACT_CONSUMER_VERSION="$(git rev-parse --short HEAD)"
          npx pact-broker@latest publish ./pacts --consumer-app-version="$PACT_CONSUMER_VERSION" --branch=main