name: Pact Publish Consumer

on:
  push:
    branches: [main]

jobs:
  pact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install --production=false
      
      - name: Run tests and generate Pact files
        run: npm run test

      - name: Publish Pacts
        run: npm run publish:pacts
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}