name: Pact Publish Consumer

on:
  push:
    branches: [main]

jobs:
  pact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install --production=false
      
      - name: Run tests and generate Pact files
        run: npm run test
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Install Pact Broker CLI
        run: gem install pact_broker-client

      - name: Publish Pacts
        run: |
          pact-broker publish ./pacts --consumer-app-version="$(git rev-parse --short HEAD)" --branch=main
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}